In [2]:
import numpy as np


## Array Summation

In [3]:
A = [[1,2,3],[4,5,6],[7,8,9]]
print(np.sum(A))
print(np.sum(A, axis = None))
print(np.sum(A, axis = 0)) # um will be in column wise..!
print(np.sum(A, axis = 1)) # Sum will be in row wise..!
print(np.sum(A, axis = 0, keepdims = True)) # um will be in column wise..!
print(np.sum(A, axis = 1, keepdims = True)) # Sum will be in row wise..!

45
45
[12 15 18]
[ 6 15 24]
[[12 15 18]]
[[ 6]
 [15]
 [24]]


## Broadcasting + Summation in Neural Networks

### ***Broadcasting Rules***

### ***Rule 1 — Compare shapes from RIGHT to LEFT***

A.shape = (3, 1, 4)

B.shape = (    5, 4)

Aligned:   ((3  1  4), (1  5  4))

### ***Rule 2 — Dimensions must be either:***

Equal, OR

- One of them is 1, OR

- One of them is missing (i.e., shorter shape is padded on the left)

- If these conditions fail → broadcasting error.

### ***Rule 3 — Dimension of size 1 is "stretched"***

A dimension with size 1 expands automatically to match the other dimension.

Example:

X: (3, 1)

Y: (3, 4)

Broadcast result shape:

(3, 4)

Because (3,1) expands into:

(3,4)


## Broadcasting Examples

***Example 1 — Scalar + Array***

a = np.array([1, 2, 3])

b = 5

a + b


b → broadcast to [5, 5, 5].

***Example 2 — (3,4) + (1,4)***

A: (3,4)

B: (1,4)


(1,4) expands to (3,4) → valid.

***Example 3 — (3,1) + (3,4)***

A: (3,1)

B: (3,4)


(3,1) expands to (3,4) → valid.

***Example 4 — Invalid***

A: (3,4)

B: (2,4)


Compare last → 4 = 4 (OK)

Compare next → 3 vs 2 (❌ neither is 1)

→ Broadcasting error

## Broadcasting in Neural Networks

### ***Weights × Inputs + Biases***

***output = np.dot(X, W) + b***

X shape → (n_samples, n_features)

W shape → (n_features, n_neurons)

b shape → (1, n_neurons)

***Biases broadcast to match all rows of output.***

You get:

(n_samples, n_neurons)


- NumPy handles broadcasting automatically.

***np.dot(X, W) → (n_samples, n_neurons)***

***bias b       → (1, n_neurons)***

In [4]:
import numpy as np

X = np.array([
    [1, 2, 3, 2.5],
    [2, 5, -1, 2],
    [-1.5, 2.7, 3.3, -0.8]
])   # shape (3,4)

W = np.array([
    [0.2, 0.8, -0.5],
    [0.5, -0.91, 0.26],
    [-0.26, -0.27, 0.17],
    [1.0, -0.5, 0.87]
])   # shape (4,3)

b = np.array([[2, 3, 0.5]])   # shape (1,3)


In [5]:
Z = np.dot(X, W)

# Result shape:
# X   = (3,4)
# W   = (4,3)
# Z   = (3,3)

'''
Example: 
z = 
[
 [4.8, 1.21, 2.385],
 [8.9, -1.81, 0.2],
 [1.41, 1.051, 0.026]
]
'''

'\nExample: \nz = \n[\n [4.8, 1.21, 2.385],\n [8.9, -1.81, 0.2],\n [1.41, 1.051, 0.026]\n]\n'

### 4. Adding Bias (Broadcasting Happens Here)

We add b:

output = Z + b

***Shapes:***

Z   = (3,3)

b   = (1,3)

Result = (3,3)


***NumPy automatically expands b to:***

[2, 3, 0.5]

[2, 3, 0.5]

[2, 3, 0.5]


***So addition becomes:***

[
 [4.8+2, 1.21+3, 2.385+0.5],

 [8.9+2, -1.81+3, 0.2+0.5],

 [1.41+2, 1.051+3, 0.026+0.5]
]